<script setup lang="ts">
import { ref } from 'vue'; import { api } from '../api'; import { parseImportFile } from '../import-file';
interface Preview { inserted:number; updated:number; invalid:number; errors?:Array<{sourceKey:string;code:string;message:string}>; document?:unknown }
const emit=defineEmits<{close:[];applied:[]}>(); const payload=ref<unknown>(), preview=ref<Preview>(), error=ref(''), busy=ref(false), mode=ref<'file'|'url'>('file'), importUrl=ref(''), fileName=ref('');
function reset(){preview.value=undefined;payload.value=undefined;error.value='';fileName.value=''}
async function loadFile(file:File){reset();fileName.value=file.name;busy.value=true;try{payload.value=parseImportFile(await file.text());preview.value=await api.send('/api/admin/import/preview','POST',payload.value)}catch(e){error.value=e instanceof Error?e.message:'文件无效'}finally{busy.value=false}}
async function choose(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(file)await loadFile(file)}
async function dropFile(event:DragEvent){if(busy.value)return;const file=event.dataTransfer?.files?.[0];if(file)await loadFile(file)}
async function fetchUrl(){if(busy.value||!importUrl.value.trim())return;reset();busy.value=true;try{const result=await api.send<Preview>('/api/admin/import/url-preview','POST',{url:importUrl.value.trim()});payload.value=result.document;preview.value=result}catch(e){error.value=e instanceof Error?e.message:'URL 导入失败'}finally{busy.value=false}}
async function apply(){if(busy.value||!payload.value)return;busy.value=true;error.value='';try{preview.value=await api.send('/api/admin/import/apply','POST',payload.value);emit('applied')}catch(e){error.value=e instanceof Error?e.message:'导入失败'}finally{busy.value=false}}
</script>
<template><div class="modal" role="dialog" aria-modal="true" @click.self="emit('close')"><section class="panel dialog"><div class="page-head"><div><div class="eyebrow">SOURCE IMPORT</div><h2>导入视频源</h2></div><button class="ghost" :disabled="busy" @click="emit('close')">✕</button></div><div class="actions"><button :class="mode==='file'?'primary':'ghost'" :disabled="busy" @click="mode='file';reset()">本地文件</button><button :class="mode==='url'?'primary':'ghost'" :disabled="busy" @click="mode='url';reset()">从 URL</button></div><div v-if="mode==='file'" class="drop" @dragover.prevent @drop.prevent="dropFile"><div class="upload-icon" aria-hidden="true">⇧</div><b>点击或拖拽文件到这里</b><p>支持 LunaTV JSON 和 Base58 格式</p><label class="upload-button">选择文件<input class="file-input" type="file" accept="application/json,.json,.txt,text/plain" :disabled="busy" @change="choose"></label><div v-if="fileName" class="selected-file" :title="fileName">✓ {{fileName}}</div></div><form v-else class="url-import-form" @submit.prevent="fetchUrl"><label><span>订阅 URL</span><input v-model="importUrl" type="url" required placeholder="https://example.com/sources" :disabled="busy"></label><button class="primary" type="submit" :disabled="busy||!importUrl.trim()">获取并预览</button></form><p v-if="busy" role="status">正在处理…</p><p v-if="error" class="error" role="alert">{{error}}</p><template v-if="preview"><div class="preview"><b>新增 {{preview.inserted}}</b><b>更新 {{preview.updated}}</b><b :class="{bad:preview.invalid}">无效 {{preview.invalid}}</b></div><ul v-if="preview.errors?.length" class="errors"><li v-for="item in preview.errors" :key="item.sourceKey+item.code"><code>{{item.sourceKey||'(空键)'}}</code>：{{item.message}}</li></ul><p v-else class="good">校验通过，可以应用。</p><footer><button class="ghost" :disabled="busy" @click="emit('close')">取消</button><button class="primary" :disabled="busy||!payload" @click="apply">应用有效条目</button></footer></template></section></div></template>
