<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'; import { api } from '../api'; import SourceEditor from '../components/SourceEditor.vue'; import ImportDialog from '../components/ImportDialog.vue';
interface Source {id:number;sourceKey:string;name:string;api:string;classificationMode:'auto'|'normal'|'adult';isAdult:boolean;enabled:boolean;ignoreHealthCheck:boolean;healthStatus:'unknown'|'healthy'|'unhealthy';latencyMs:number|null;lastCheckedAt:string|null;detail:string|null;comment:string|null}
const result=ref<{items:Source[];total:number;page:number;pageSize:number}>({items:[],total:0,page:1,pageSize:25});const filters=reactive({search:'',classification:'',healthStatus:'',enabled:''});const selected=ref<number[]>([]),busy=ref(false),error=ref(''),editor=ref<Source|null|undefined>(),showImport=ref(false);let timer:number;
const pages=computed(()=>Math.max(1,Math.ceil(result.value.total/result.value.pageSize)));const allSelected=computed(()=>result.value.items.length>0&&result.value.items.every(s=>selected.value.includes(s.id)));
async function load(page=result.value.page){busy.value=true;error.value='';try{const q=new URLSearchParams({page:String(page),pageSize:'25'});Object.entries(filters).forEach(([k,v])=>v&&q.set(k,v));result.value=await api.get(`/api/admin/sources?${q}`);selected.value=[]}catch(e){error.value=e instanceof Error?e.message:'载入失败'}finally{busy.value=false}}
watch(filters,()=>{clearTimeout(timer);timer=window.setTimeout(()=>load(1),250)},{deep:true});function toggleAll(){selected.value=allSelected.value?[]:result.value.items.map(s=>s.id)}
async function action(action:'enable'|'disable'|'delete'|'check'){if(!selected.value.length)return;if(action==='delete'&&!confirm(`确定删除 ${selected.value.length} 个来源？`))return;busy.value=true;try{await api.send('/api/admin/sources/bulk','POST',{ids:selected.value,action});await load()}catch(e){error.value=e instanceof Error?e.message:'操作失败'}finally{busy.value=false}}
async function remove(s:Source){if(!confirm(`确定删除“${s.name}”？`))return;try{await api.send(`/api/admin/sources/${s.id}`,'DELETE');await load()}catch(e){error.value=e instanceof Error?e.message:'删除失败'}}
async function check(s:Source){try{await api.send(`/api/admin/sources/${s.id}/check`,'POST');await load()}catch(e){error.value=e instanceof Error?e.message:'检测失败'}}
async function removeUnhealthy(){if(!confirm('确定移除所有异常来源？此操作无法撤销。'))return;busy.value=true;error.value='';try{const response=await api.send<{affected:number}>('/api/admin/sources/remove-unhealthy','POST');await load(1);if(response.affected===0)error.value='当前没有异常来源'}catch(e){error.value=e instanceof Error?e.message:'移除失败'}finally{busy.value=false}}
onMounted(()=>load(1));
</script>
<template><section><div class="page-head"><div><div class="eyebrow">SOURCES</div><h1>视频源管理</h1><p class="muted">共 {{result.total}} 个来源</p></div><div class="actions"><button class="ghost danger-button" :disabled="busy" @click="removeUnhealthy">移除异常</button><button class="ghost" @click="showImport=true">导入视频源</button><button class="primary" @click="editor=null">＋ 添加视频源</button></div></div><div class="filters panel"><label><span class="sr-only">搜索</span><input v-model="filters.search" type="search" placeholder="搜索名称、键或 API"></label><select v-model="filters.classification" aria-label="分类"><option value="">全部分类</option><option value="normal">普通</option><option value="adult">成人</option></select><select v-model="filters.healthStatus" aria-label="健康状态"><option value="">全部状态</option><option value="healthy">健康</option><option value="unhealthy">异常</option><option value="unknown">未检测</option></select><select v-model="filters.enabled" aria-label="启用状态"><option value="">全部启用状态</option><option value="true">已启用</option><option value="false">已停用</option></select></div><div v-if="selected.length" class="bulk"><b>已选 {{selected.length}} 项</b><button @click="action('enable')">启用</button><button @click="action('disable')">停用</button><button @click="action('check')">检测</button><button class="danger" @click="action('delete')">删除</button></div><p v-if="error" class="error" role="alert">{{error}}</p><div class="table-wrap panel"><table><thead><tr><th><input type="checkbox" :checked="allSelected" aria-label="选择本页全部" @change="toggleAll"></th><th>来源</th><th>分类</th><th>状态</th><th>启用</th><th>操作</th></tr></thead><tbody><tr v-if="busy&&!result.items.length"><td colspan="6">载入中…</td></tr><tr v-else-if="!result.items.length"><td colspan="6" class="empty">没有符合条件的来源</td></tr><tr v-for="s in result.items" :key="s.id"><td><input v-model="selected" type="checkbox" :value="s.id" :aria-label="`选择 ${s.name}`"></td><td><b>{{s.name}}</b><code>{{s.sourceKey}}</code><small class="truncate" :title="s.api">{{s.api}}</small></td><td><span class="tag">{{s.isAdult?'成人':'普通'}}</span></td><td><span :class="['status',s.healthStatus]">{{s.healthStatus==='healthy'?'健康':s.healthStatus==='unhealthy'?'异常':'未检测'}}</span><small v-if="s.latencyMs!==null">{{s.latencyMs}} ms</small></td><td>{{s.enabled?'是':'否'}}</td><td><div class="row-actions"><button class="link" @click="editor=s">编辑</button><button class="link" @click="check(s)">检测</button><button class="link danger" @click="remove(s)">删除</button></div></td></tr></tbody></table></div><div class="pager"><button :disabled="result.page<=1||busy" @click="load(result.page-1)">上一页</button><span>{{result.page}} / {{pages}}</span><button :disabled="result.page>=pages||busy" @click="load(result.page+1)">下一页</button></div><SourceEditor v-if="editor!==undefined" :source="editor||undefined" @close="editor=undefined" @saved="editor=undefined;load()"/><ImportDialog v-if="showImport" @close="showImport=false" @applied="showImport=false;load(1)"/></section></template>
